### ISSUE TITLE
Deprecation warning about `Project.getConvention()` when run using gradle 8.2.1

### ISSUE THREAD

**Issue by AndreasBoehm** [Triple-T/gradle-play-publisher#1094]
### Problem description
The Project.getConvention() method has been deprecated.	
This is scheduled to be removed in Gradle 9.0.	
[Documentation](https://docs.gradle.org/8.2.1/userguide/upgrading_version_8.html#deprecated_access_to_conventions)	
Plugin: `com.github.triplet.play`
```
at org.gradle.api.internal.project.DefaultProject.getConvention(DefaultProject.java:593)	
at com.github.triplet.gradle.play.PlayPublisherPlugin.applyInternal(PlayPublisherPlugin.kt:904)	
at com.github.triplet.gradle.play.PlayPublisherPlugin.access$applyInternal(PlayPublisherPlugin.kt:71)	
at com.github.triplet.gradle.play.PlayPublisherPlugin$apply$2.invoke(PlayPublisherPlugin.kt:87)	
at com.github.triplet.gradle.play.PlayPublisherPlugin$apply$2.invoke(PlayPublisherPlugin.kt:86)	
at com.github.triplet.gradle.play.PlayPublisherPlugin$inlined$sam$i$org_gradle_api_Action$0.execute(DomainObjectCollectionExtensions.kt)	
•••
at com.github.triplet.gradle.play.PlayPublisherPlugin.apply(PlayPublisherPlugin.kt:689)	
at com.github.triplet.gradle.play.PlayPublisherPlugin.apply(PlayPublisherPlugin.kt:71)
```

### Additional context
I used `gradle 8.2.1` and [Gradle Play Publisher 3.8.4](https://github.com/Triple-T/gradle-play-publisher/releases/tag/3.8.4)

**Comment by AndreasBoehm** [comment]
This was closed without being fixed.

**Comment by syslogic** [comment]
It seems to be the way, how the `PlayPublisherExtension` is being configured:

https://github.com/Triple-T/gradle-play-publisher/blob/df4eadf1ca6b5bad50e21be0b21816722ed50342/play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt#L78C1-L84C10

**Comment by edharkhimich** [comment]
Any updates on this?

**Comment by Goooler** [comment]
Fixing this in #1113. I don't see the line in your stacktrace (`PlayPublisherPlugin.kt:904`), but I guess this is due to

https://github.com/Triple-T/gradle-play-publisher/blob/19dc9a6e712f3a839b59b90cee8697f15de0df70/play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt#L181

check

https://github.com/gradle/gradle/blob/1cf537a851c635c364a4214885f8b9798051175b/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/ProjectExtensions.kt#L100-L112

**Comment by SUPERCILEX** [comment]
Can someone confirm with snapshot builds that this is fixed? (Those should go out within the hour.)

**Comment by PavelSynek** [comment]
I confirm that the warning is fixed with snapshot build.
