### ISSUE TITLE
bootstrapReleaseListing: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"

### ISSUE THREAD

**Issue by dumasmcarvalho** [Triple-T/gradle-play-publisher#1100]
### Describe the bug

When executing the command mentioned in the "Tasks executed" section, I am receiving an error related to the task `bootstrapReleaseListing`, the error indicates that there is something related to the proxy used in our CI/CD environment. See the issue details in the "Additional context" section.

#### Versions
```
\--- com.github.triplet.play:com.github.triplet.play.gradle.plugin:3.8.4
     \--- com.github.triplet.gradle:play-publisher:3.8.4
          +--- com.github.triplet.gradle:android-publisher:3.8.4
          |    +--- com.github.triplet.gradle:common-utils:3.8.4
          +--- com.github.triplet.gradle:common-utils:3.8.4
          +--- com.github.triplet.gradle:common-validation:3.8.4
Gradle 7.3.3
+--- com.android.tools.build:gradle:7.2.1
```

#### Tasks executed
`./gradlew bootstrapListing --info --stacktrace`

### Expected behavior
The command execution should be successful for the task mentioned (`bootstrapReleaseListing`).

Is it necessary to include another domain in our proxy rules for the `bootstrapReleaseListing` task to work? I believed that only the following would be required for Gradle Play Publisher to work:
- `*.googleapis.com:443/HTTPS`
- `*.googleusercontent.com:443/HTTPS`

### Additional context (if a crash, provide stack trace)
I'm using the following settings for the proxy:
```
export HTTP_PROXY="http://myproxy.com.br:80"
export HTTPS_PROXY="http://myproxy.com.br:80"
export NO_PROXY="localhost,mygitlab.com.br,registry.gitlab.com"
export JAVA_OPTS="-Djdk.http.auth.tunneling.disabledSchemes='' -Djdk.http.auth.proxying.disabledSchemes='' -Dhttp.proxyHost=myproxy.com.br -Dhttp.proxyPort=80 -Dhttps.proxyHost=myproxy.com.br -Dhttps.proxyPort=80 '-Dhttp.nonProxyHosts=localhost|mygitlab.com.br|registry.gitlab.com'"
```

For security reasons, I can't provide the full log (and I had to mask some information with the expression "xyz"), but here is the part where the error occurs:
- In the log below, the error occurred when entering the function `Downloading pt-BR listing graphics for type 'phoneScreenshots'`, however there are executions where failure occurs in the previous function `Downloading pt-BR listing graphics for type 'icon'`, for some reason, the order of functions is sometimes reversed and the error always occurs in the last function executed (be it 'phoneScreenshots' or 'icon').

```
[...]
Downloading pt-BR listing
-------------- REQUEST  --------------
GET https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/icon
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)
x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0
curl -v --compressed -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)' -H 'x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0' -- 'https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/icon'
-------------- REQUEST  --------------
GET https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/phoneScreenshots
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)
x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0
curl -v --compressed -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)' -H 'x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0' -- 'https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/phoneScreenshots'
-------------- REQUEST  --------------
GET https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/tenInchScreenshots
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)
x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0
curl -v --compressed -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)' -H 'x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0' -- 'https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/tenInchScreenshots'
-------------- REQUEST  --------------
GET https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/featureGraphic
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)
x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0
-------------- REQUEST  --------------
GET https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/sevenInchScreenshots
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)
x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0
-------------- REQUEST  --------------
GET https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/wearScreenshots
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)
x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0
curl -v --compressed -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)' -H 'x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0' -- 'https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/sevenInchScreenshots'
curl -v --compressed -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)' -H 'x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0' -- 'https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/wearScreenshots'
curl -v --compressed -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)' -H 'x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0' -- 'https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/featureGraphic'
-------------- REQUEST  --------------
GET https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/tvBanner
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)
x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0
curl -v --compressed -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)' -H 'x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0' -- 'https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/tvBanner'
-------------- REQUEST  --------------
GET https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/tvScreenshots
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)
x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0
curl -v --compressed -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: gradle-play-publisher Google-API-Java-Client/2.2.0 Google-HTTP-Java-Client/1.42.3 (gzip)' -H 'x-goog-api-client: gl-java/11.0.19 gdcl/2.2.0 linux/4.18.0' -- 'https://androidpublisher.googleapis.com/androidpublisher/v3/applications/xyz/edits/xyz/listings/pt-BR/tvScreenshots'
-------------- RESPONSE --------------
HTTP/1.1 200 OK
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Cache-Control: private
Server: ESF
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Vary: Referer
Vary: X-Origin
Vary: Origin
X-XSS-Protection: 0
Date: Wed, 20 Sep 2023 22:32:14 GMT
Content-Type: application/json; charset=UTF-8
Total: 3 bytes
{}
-------------- RESPONSE --------------
HTTP/1.1 200 OK
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Cache-Control: private
Server: ESF
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Vary: Referer
Vary: X-Origin
Vary: Origin
X-XSS-Protection: 0
Date: Wed, 20 Sep 2023 22:32:14 GMT
Content-Type: application/json; charset=UTF-8
Total: 3 bytes
{}
-------------- RESPONSE --------------
HTTP/1.1 200 OK
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Cache-Control: private
Server: ESF
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Vary: Referer
Vary: X-Origin
Vary: Origin
X-XSS-Protection: 0
Date: Wed, 20 Sep 2023 22:32:14 GMT
Content-Type: application/json; charset=UTF-8
Total: 328 bytes
{
  "images": [
    {
      "id": "xyz",
      "url": "https://lh3.googleusercontent.com/xyz",
      "sha1": "xyz",
      "sha256": "xyz"
    }
  ]
}
Downloading pt-BR listing graphics for type 'icon'
-------------- RESPONSE --------------
HTTP/1.1 200 OK
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Cache-Control: private
Server: ESF
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Vary: Referer
Vary: X-Origin
Vary: Origin
X-XSS-Protection: 0
Date: Wed, 20 Sep 2023 22:32:14 GMT
Content-Type: application/json; charset=UTF-8
-------------- RESPONSE --------------
HTTP/1.1 200 OK
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Cache-Control: private
Server: ESF
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Vary: Referer
Vary: X-Origin
Vary: Origin
X-XSS-Protection: 0
Date: Wed, 20 Sep 2023 22:32:14 GMT
Content-Type: application/json; charset=UTF-8
Total: 3 bytes
{}
-------------- RESPONSE --------------
HTTP/1.1 200 OK
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Cache-Control: private
Server: ESF
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Vary: Referer
Vary: X-Origin
Vary: Origin
X-XSS-Protection: 0
Date: Wed, 20 Sep 2023 22:32:14 GMT
Content-Type: application/json; charset=UTF-8
Total: 3 bytes
{}
Total: 3 bytes
{}
-------------- RESPONSE --------------
HTTP/1.1 200 OK
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Cache-Control: private
Server: ESF
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Vary: Referer
Vary: X-Origin
Vary: Origin
X-XSS-Protection: 0
Date: Wed, 20 Sep 2023 22:32:14 GMT
Content-Type: application/json; charset=UTF-8
Total: 328 bytes
{
  "images": [
    {
      "id": "xyz",
      "url": "https://lh3.googleusercontent.com/xyz",
      "sha1": "xyz",
      "sha256": "xyz"
    }
  ]
}
Downloading pt-BR listing graphics for type 'featureGraphic'
-------------- RESPONSE --------------
HTTP/1.1 200 OK
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Cache-Control: private
Server: ESF
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Vary: Referer
Vary: X-Origin
Vary: Origin
X-XSS-Protection: 0
Date: Wed, 20 Sep 2023 22:32:14 GMT
Content-Type: application/json; charset=UTF-8
Total: 2,478 bytes
{
  "images": [
    {
      "id": "xyz",
      "url": "https://lh3.googleusercontent.com/xyz",
      "sha1": "xyz",
      "sha256": "xyz"
    },
    {
      "id": "xyz",
      "url": "https://lh3.googleusercontent.com/xyz",
      "sha1": "xyz",
      "sha256": "xyz"
    },
    {
      "id": "xyz",
      "url": "https://lh3.googleusercontent.com/xyz",
      "sha1": "xyz",
      "sha256": "xyz"
    },
    {
      "id": "xyz",
      "url": "https://lh3.googleusercontent.com/xyz",
      "sha1": "xyz",
      "sha256": "xyz"
    },
    {
      "id": "xyz",
      "url": "https://lh3.googleusercontent.com/xyz",
      "sha1": "xyz",
      "sha256": "xyz"
    },
    {
      "id": "xyz",
      "url": "https://lh3.googleusercontent.com/xyz",
      "sha1": "xyz",
      "sha256": "xyz"
    },
    {
      "id": "xyz",
      "url": "https://lh3.googleusercontent.com/xyz",
      "sha1": "xyz",
      "sha256": "xyz"
    },
    {
      "id": "xyz",
      "url": "https://lh3.googleusercontent.com/xyz",
      "sha1": "xyz",
      "sha256": "xyz"
    }
  ]
}
Downloading pt-BR listing graphics for type 'phoneScreenshots'
> Task :app:bootstrapReleaseListing FAILED
:app:bootstrapReleaseListing (Thread[Execution worker for ':',5,main]) completed. Took 4.762 secs.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:bootstrapReleaseListing'.
> A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ListingsDownloader
   > There were multiple failures while executing work items
      > A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageFetcher
         > There was a failure while executing work items
            > A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageDownloader
               > Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
      > A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageFetcher
         > There was a failure while executing work items
            > A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageDownloader
               > Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
      > A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageFetcher
         > There were multiple failures while executing work items
            > A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageDownloader
               > Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
            > A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageDownloader
               > Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
            > A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageDownloader
               > Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
            > A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageDownloader
               > Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
            > A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageDownloader
               > Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
            > A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageDownloader
               > Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
            > A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageDownloader
               > Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
            > A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageDownloader
               > Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
* Try:
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:bootstrapReleaseListing'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:145)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:143)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:402)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:389)
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
1 actionable task: 1 executed
Some of the file system contents retained in the virtual file system are on file systems that Gradle doesn't support watching. The relevant state was discarded to ensure changes to these locations are properly detected. You can override this by explicitly enabling file system watching.
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:382)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:368)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ListingsDownloader
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:208)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:214)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
Caused by: org.gradle.workers.WorkerExecutionException: There were multiple failures while executing work items
	at org.gradle.workers.internal.DefaultWorkerExecutor.workerExecutionException(DefaultWorkerExecutor.java:272)
	at org.gradle.workers.internal.DefaultWorkerExecutor.await(DefaultWorkerExecutor.java:252)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:72)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:206)
	... 6 more
Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageFetcher
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:208)
	... 6 more
Caused by: org.gradle.workers.WorkerExecutionException: There was a failure while executing work items
	at org.gradle.workers.internal.DefaultWorkerExecutor.workerExecutionException(DefaultWorkerExecutor.java:270)
	at org.gradle.workers.internal.DefaultWorkerExecutor.await(DefaultWorkerExecutor.java:252)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:72)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:206)
	... 6 more
Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageDownloader
	at org.gradle.workers.internal.DefaultWorkerExecutor$WorkItemExecution.waitForCompletion(DefaultWorkerExecutor.java:342)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:142)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:90)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForAll(DefaultAsyncWorkTracker.java:80)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForCompletion(DefaultAsyncWorkTracker.java:68)
	at org.gradle.workers.internal.DefaultWorkerExecutor.await(DefaultWorkerExecutor.java:250)
	... 20 more
Caused by: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
	at com.github.triplet.gradle.play.tasks.Bootstrap$ImageDownloader.execute(Bootstrap.kt:184)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
	... 19 more
* Get more help at https://help.gradle.org
BUILD FAILED in 6s
```

**Comment by dumasmcarvalho** [comment]
Update:

I saved the "app/src/main/play" folder and noticed that everything was generated successfully, except the image files (listings/pt-BR/graphics), all of which had no extension.

Locally, without network restrictions or proxy usage, everything is downloaded normally.

Therefore, I believe that it really is some additional proxy configuration that would be necessary, is there any suggestion of what could be done?

Results from our CI/CD (with network restrictions and proxy): 
![image](https://github.com/Triple-T/gradle-play-publisher/assets/32886449/53d37a44-3e6d-49f4-b129-53501a018ca5)

Results from the locally execution:
![image](https://github.com/Triple-T/gradle-play-publisher/assets/32886449/9081e903-2082-4e6e-b58f-9e55a5ac9536)
