### ISSUE TITLE
Enabling AUTO version bump causes exception in gradle

### ISSUE THREAD

**Issue by bpappin-atimi** [Triple-T/gradle-play-publisher#1139]
### Describe the bug

When you enable resolutionStrategy.set(com.github.triplet.gradle.androidpublisher.ResolutionStrategy.AUTO)
you get an error:<app>/build/intermediates/gpp/atimiQa/available-version-codes.txt (No such file or directory)

This only happens when I specifically enable that property.

#### Versions

<!--
Run this command to get all the version info you need:
```
+--- com.github.triplet.play:com.github.triplet.play.gradle.plugin:3.10.1
|    \--- com.github.triplet.gradle:play-publisher:3.10.1
|         +--- com.github.triplet.gradle:android-publisher:3.10.1
|         |    +--- com.github.triplet.gradle:common-utils:3.10.1
|         +--- com.github.triplet.gradle:common-utils:3.10.1
|         +--- com.github.triplet.gradle:common-validation:3.10.1
Gradle 8.7
|    \--- com.android.tools.build:gradle:8.5.1
|    \--- com.android.tools.build:gradle:8.5.1 (*)
```

#### Tasks executed

./gradlew publishVariantNameBundle

### Expected behavior

I expectd the version number to roll over when already taken.

### Additional context (if a crash, provide stack trace)

```
Caused by: java.io.FileNotFoundException: /Users/bpappin/Workspace/arcturus-android/app/build/intermediates/gpp/atimiQa/available-version-codes.txt (No such file or directory)
	at kotlin.io.FilesKt__FileReadWriteKt.forEachLine(FileReadWrite.kt:190)
	at kotlin.io.FilesKt__FileReadWriteKt.readLines(FileReadWrite.kt:219)
	at kotlin.io.FilesKt__FileReadWriteKt.readLines$default(FileReadWrite.kt:217)
	at org.gradle.internal.classpath.MethodHandleUtils.invokeKotlinStaticDefault(MethodHandleUtils.java:42)
	at org.gradle.internal.classpath.declarations.KotlinStdlibFileInterceptors.intercept_readLines(KotlinStdlibFileInterceptors.java:109)
	at com.github.triplet.gradle.play.PlayPublisherPlugin$applyInternal$1$10.transform(PlayPublisherPlugin.kt:441)
	at com.github.triplet.gradle.play.PlayPublisherPlugin$applyInternal$1$10.transform(PlayPublisherPlugin.kt:440)
	at org.gradle.api.internal.provider.ValueSupplier$Present.transform(ValueSupplier.java:511)
```

**Comment by bpappin** [comment]
So file a bug, nobody looks at it, and it's automatically closed?

That doesn't sound like a winning strategy.

**Comment by SUPERCILEX** [comment]
Added some clarification: https://github.com/Triple-T/gradle-play-publisher/commit/6a0e6c12a8ffa535714a816ad5e8f8539abb8c4c

I'm not going to do anything about it and a lot of issues are spammy hence auto closing them. If you need this fixed, I accept PRs.

**Comment by warting** [comment]
@bpappin-atimi  as a workaround you can create an empty file before building. Just stumble up on the same issue. 

```
mkdir -p build/intermediates/gpp/atimiQa
touch build/intermediates/gpp/atimiQa/available-version-codes.txt
```

**Comment by pitampoudel** [comment]
Facing the same issue
`USER\composeApp\build\intermediates\gpp\godaanRelease\available-version-codes.txt (The system cannot find the file specified)
`
when using   resolutionStrategy.set(ResolutionStrategy.AUTO)
