### ISSUE TITLE
Error : toDerInputStream rejects tag type -116

### ISSUE THREAD

**Issue by ihsanbal** [Triple-T/gradle-play-publisher#209]
> Version
`classpath 'com.github.triplet.gradle:play-publisher:1.2.0'`

> Configurations
```
android {
playAccountConfigs {
        defaultAccountConfig {
            serviceAccountEmail = 'myKey@developer.gserviceaccount.com'
            pk12File = rootProject.file('.keystore/release.p12.gpg')
        }
    }

    defaultConfig {
        multiDexEnabled true
        playAccountConfig = playAccountConfigs.defaultAccountConfig
    }
}

play {
    track = 'beta'
    untrackOld = true
}
```

> Stacktrace

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:publishListingProductionRelease'.
> java.io.IOException: toDerInputStream rejects tag type -116

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:publishListingProductionRelease'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: org.gradle.api.UncheckedIOException: java.io.IOException: toDerInputStream rejects tag type -116
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 20 more
Caused by: java.io.IOException: toDerInputStream rejects tag type -116
        at com.google.api.client.util.SecurityUtils.loadKeyStore(SecurityUtils.java:82)
        at com.google.api.client.util.SecurityUtils.loadPrivateKeyFromKeyStore(SecurityUtils.java:115)
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential$Builder.setServiceAccountPrivateKeyFromP12File(GoogleCredential.java:671)
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential$Builder$setServiceAccountPrivateKeyFromP12File$3.call(Unknown Source)
        at de.triplet.gradle.play.AndroidPublisherHelper.authorizeWithServiceAccount(AndroidPublisherHelper.groovy:57)
        at de.triplet.gradle.play.AndroidPublisherHelper.authorizeWithServiceAccount(AndroidPublisherHelper.groovy:43)
        at de.triplet.gradle.play.AndroidPublisherHelper.init(AndroidPublisherHelper.groovy:86)
        at de.triplet.gradle.play.PlayPublishTask.publish(PlayPublishTask.groovy:28)
        at de.triplet.gradle.play.PlayPublishTask$publish.callCurrent(Unknown Source)
        at de.triplet.gradle.play.PlayPublishListingTask.publishListing(PlayPublishListingTask.groovy:45)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        ... 27 more


BUILD FAILED

```

at PlayPublishTask.groovy:28 try to authorizeWithServiceAccount(config.jsonFile) but I'm not using jsonFile.

**Comment by SUPERCILEX** [comment]
Are you still experiencing this issue?

**Comment by ihsanbal** [comment]
Nope!
