### ISSUE TITLE
publish task fails on gradle 4.0 and gradle plugin 3.0.0.-alpha1

### ISSUE THREAD

**Issue by dannyroa** [Triple-T/gradle-play-publisher#216]
I'm getting the following error after I upgraded gradle to 4.0-milestone and gradle plugin to 3.0.0.-alpha1.

Looks like related to https://issuetracker.google.com/issues/38408231

```
Caused by: java.lang.RuntimeException: Not valid.
        at com.android.ide.common.build.ApkData.getMainOutputFile(ApkData.java:136)
        at com.android.build.gradle.internal.api.BaseVariantOutputImpl.getOutputFile(BaseVariantOutputImpl.java:60)
        at com.android.build.gradle.internal.api.ApkVariantOutputImpl_Decorated.getOutputFile(Unknown Source)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
```

**Comment by NiKoTron** [comment]
fixed in gradle plugin to 3.0.0.-alpha**2**

**Comment by cwliu** [comment]
I also got this error when I upgrade to Android Studio 3.0 Canary 2. The following is my workaround: 

1. Go to `File > Project Structure`. Click `Project` section
2. Downgrade `Gradle version` to `3.3` and `Android plugin version` to `2.3.2`

**Comment by dannyroa** [comment]
@cwliu: That doesn't work for us because we already made changes specific to the latest gradle plugin. We're also running this on CI.

**Comment by OrdonTeam** [comment]
@dannyroa 
Here is change set that fixed same issue in our project:
https://github.com/elpassion/el-space-android/commit/f2ac5a7dd1c0c176e3444e7e87b8c851e994638a

**Comment by cypressious** [comment]
@OrdonTeam Can you create a pull request with the fix?

**Comment by OrdonTeam** [comment]
Use build tools gradle plugin 3.0.0-alpha4.

**Comment by ChristianBecker** [comment]
The current version of the plugin is properly working on 3.x.y
