### ISSUE TITLE
Invalid PKCS8 data

### ISSUE THREAD

**Issue by nscherer** [Triple-T/gradle-play-publisher#236]
I'm getting this error trying to run a bootstrap task:

Error:Execution failed for task ':app:bootstrapAppNamePlayResources'. java.io.IOException: Invalid PKCS8 data.

Stack trace:

```
Caused by: java.io.IOException: Invalid PKCS8 data.
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.privateKeyFromPkcs8(GoogleCredential.java:812)
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.fromStreamServiceAccount(GoogleCredential.java:788)
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.fromStream(GoogleCredential.java:260)
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential$fromStream.call(Unknown Source)
        at de.triplet.gradle.play.AndroidPublisherHelper.authorizeWithServiceAccount(AndroidPublisherHelper.groovy:66)
        at de.triplet.gradle.play.AndroidPublisherHelper.authorizeWithServiceAccount(AndroidPublisherHelper.groovy:45)
        at de.triplet.gradle.play.AndroidPublisherHelper.init(AndroidPublisherHelper.groovy:86)
        at de.triplet.gradle.play.PlayPublishTask.publish(PlayPublishTask.groovy:28)
        at de.triplet.gradle.play.PlayPublishTask$publish.callCurrent(Unknown Source)
        at de.triplet.gradle.play.BootstrapTask.bootstrap(BootstrapTask.groovy:26)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
```

The last few lines of output before the error:

```
Executing task ':app:bootstrapAppNamePlayResources' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:app:bootstrapAppNamePlayResources FAILED
:app:bootstrapAppNamePlayResources (Thread[Daemon worker,5,main]) completed. Took 0.663 secs.
```

Here's how I'm configuring it:

```
    playAccountConfigs {
        defaultAccountConfig {
            jsonFile = file('Google Play Android Developer-bd451789a4fa.json')
        }
    }
```

The json file has some things in it that I assume should not be publicized but I can give some details if that would be helpful.  I have not modified the file.  I also have a p12 file that doesn't seem to be referenced from anywhere - is it possible my json file is incorrect?  Is there an example file that shows what one should have in it?  Lastly, could there be a more helpful error message supplied?  I don't know what to do with "Invalid PKCS8 data" but if it told me "Missing XYZ from json configuration file" that would be a lot more useful.

**Comment by nscherer** [comment]
Does anyone from the project monitor this issue tracker or am I just screaming into the void?

**Comment by SUPERCILEX** [comment]
@nscherer Are you still experiencing this issue?

PS: sorry for the lack of response, we've got new members on the team to help with development so things should be better going forward. 😊

**Comment by SUPERCILEX** [comment]
Closing due to lack of response.

**Comment by kawsurilu** [comment]
I am facing the same issue.

Here is the portion of the stack trace: 

java.io.IOException: Invalid PKCS#8 data. at com.google.auth.oauth2.ServiceAccountCredentials.privateKeyFromPkcs8(ServiceAccountCredentials.java:277) at com.google.auth.oauth2.ServiceAccountCredentials.fromPkcs8(ServiceAccountCredentials.java:265) at com.google.auth.oauth2.ServiceAccountCredentials.fromJson(ServiceAccountCredentials.java:195) at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:160) at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:127) at org.ums.configuration.FirebaseConfig.config(FirebaseConfig.java:39) at org.ums.configuration.FirebaseConfig.init(FirebaseConfig.java:26) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyA
