### ISSUE TITLE
New Android App Bundle

### ISSUE THREAD

**Issue by thelittlefireman** [Triple-T/gradle-play-publisher#262]
Hi,
Do you plan to integrate the new "Android App Bundle" feature ?
[https://android-developers.googleblog.com/2018/05/io-2018-everything-new-in-google-play.html](https://android-developers.googleblog.com/2018/05/io-2018-everything-new-in-google-play.html)
[https://www.youtube.com/watch?v=bViNOUeFuiQ](https://www.youtube.com/watch?v=bViNOUeFuiQ)

the new command is : 'gradlew app:bundle'
[https://youtu.be/bViNOUeFuiQ?t=14m10s](https://youtu.be/bViNOUeFuiQ?t=14m10s)

Thanks for all 
Thomas :)

**Comment by JakeWharton** [comment]
Seems like the API was updated to include them which is nice: https://developers.google.com/android-publisher/api-ref/edits/bundles. Should be a fairly straightforward change. The only problem I see is determining the developer intent as to whether they want to publish an APK or a bundle.

**Comment by gtcompscientist** [comment]
I've been trying to enable this with the intent of having parallel tasks for APKs and Bundles. Unfortunately, I'm at an impasse that I can't resolve:
Getting the Bundle API you have to use:
- `com.android.tools.build:gradle:3.2.0-alphaXX` Currently `alpha14`, and
- `com.google.apis:google-api-services-androidpublisher:v2-rev76-1.23.0`

These build just fine for the plugin. However, when I try to reference that plugin in a project that is compatible with `1.2.1-beta1`, I get the following error on Gradle Sync:
`Unable to load class 'com.google.api.client.googleapis.json.GoogleJsonResponseException'`

**Comment by gtcompscientist** [comment]
Update, with my latest push, I've got it properly trying to push the bundle (wasn't setting the right `dependsOn`), but:
- `bundle` for each `variant` isn't available the way that the `assemble` is
- Also, the `outputs` for the `variant` doesn't contain the bundle.

The first "but" is relatively trivial, but would cause the plugin to crash/fail Gradle sync for a project that doesn't use a version of Android Tools that includes the `bundle` tasks. 

The second "but" is thornier, because you would end up hunting for that file, which is 😞...

**Comment by JakeWharton** [comment]
File a bug for each and link it here. I will escalate.

**Comment by gtcompscientist** [comment]
[#79954442 Requesting bundle task being available in the ApplicationVariant](https://issuetracker.google.com/issues/79954442)

[#79951839 Gradle BundleVariantOutput should be included in the ApplicationVariant -> Outputs](https://issuetracker.google.com/issues/79951839)

**Comment by gtcompscientist** [comment]
Was able to get the bundle (albeit somewhat surreptitiously) and attempt the upload.

From my logging it appears to properly upload all of the data (~35.6MB), but there's a timeout happening inside the `upload().execute()` command.

Relevant Code: `PlayPublishBundleTask.groovy`:`Line 50`
`        def bundle = edits.bundles()
                .upload(variant.applicationId, editId, bundleFile)
                .execute()`
Stack trace:
`org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':client:publishBundleClutchProdRelease'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.UncheckedIOException: java.net.SocketTimeoutException: Read timed out
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:57)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 30 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:105)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
        at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequestWithoutGZip(MediaHttpUploader.java:545)
        at com.google.api.client.googleapis.media.MediaHttpUploader.resumableUpload(MediaHttpUploader.java:417)
        at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:336)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:427)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$execute.call(Unknown Source)
        at de.triplet.gradle.play.PlayPublishBundleTask.publishBundle(PlayPublishBundleTask.groovy:52)
        at de.triplet.gradle.play.PlayPublishBundleTask$_publishBundle_closure2.doCall(PlayPublishBundleTask.groovy:34)
        at de.triplet.gradle.play.PlayPublishBundleTask.publishBundle(PlayPublishBundleTask.groovy:32)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        ... 42 more
`

**Comment by SUPERCILEX** [comment]
Yeah, you'll want to go into the [helper file](https://github.com/Triple-T/gradle-play-publisher/blob/master/src/main/groovy/de/triplet/gradle/play/AndroidPublisherHelper.groovy#L96) and wrap the credential in an intercepter which boosts the timeouts. I was going to share my fork with everyone a few days ago, but I get a weird [404 everytime](https://stackoverflow.com/q/50325345/4548500) I try uploading. I've contacted support so we'll see how that goes.

**Comment by gtcompscientist** [comment]
🤦‍♂️  Great tip, @SUPERCILEX, definitely helped.

However, it appears there's another issue in the API with uploading secondary data:
[#79951879 Unable to upload deobfuscation files through API after uploading bundle through API](https://issuetracker.google.com/issues/79951879)
[#79951880 Unable to upload "What's New" text through API after uploading bundle through API](https://issuetracker.google.com/issues/79951880)

Digging into the API a little more, it looks like there may be a deeper change needed in how the plugin handles the "What's New" (See: [Edit.tracks](https://developers.google.com/android-publisher/api-ref/edits/tracks))

**Comment by JakeWharton** [comment]
Just a heads up that those two issues might be closed since they're problems with the Google Play Developer API and not Android Gradle itself. If they are I'll file them internally. I would also look for a place to report feedback directly to the Google Play Developer team on their website/documentation.

**Comment by SUPERCILEX** [comment]
Yeah, I used the question icon on the Play Console to file a support request. I'll update this issue whenever it gets resolved, but dunno if @gtcompscientist you want to file a request too anyway.

**Comment by gtcompscientist** [comment]
I'll submit one when I get back to my machine, I should have realized I needed to submit those there.

**Comment by bhurling** [comment]
@gtcompscientist looks like they released a v3 of their client library to support the new tracks/releases structure: `com.google.apis:google-api-services-androidpublisher:v3-rev3-1.23.0` but it requires some refactoring of the publishing tasks. Wanna give it a shot?

**Comment by gtcompscientist** [comment]
Thinking more about this, I don't think we should add a task for this, you're either uploading Bundles or APKs, so it should probably be a configuration flag. This, of course, assumes that some of the previously mentioned issues are corrected anytime soon.

**Comment by knordbo** [comment]
Any estimate on when this will be available from the snapshot release? Would be awesome to try out.

**Comment by SUPERCILEX** [comment]
@knordbo I'll see if we can get this in a snapshot build tomorrow. (The code is there, it's just waiting to be reviewed)

**Comment by knordbo** [comment]
@SUPERCILEX cheers!

**Comment by hardysim** [comment]
So it's done? Great 👍 

Which version / snapshot do I need? And how do I enable it to output an App Bundle instead of an APK?

**Comment by SUPERCILEX** [comment]
There are a new set of tasks:
- `publishBundle` - publish all variants
- `publishReleaseBundle` - for specific variants

If you're using `publish`, you'll want to enable bundles:
```groovy
play {
    // ...
    defaultToAppBundles = true
}
```

This is false by default because App Bundles require Google Play App signing.

The snapshot build instructions are available [here](https://github.com/Triple-T/gradle-play-publisher#snapshot-builds).

**Comment by peterfortuin** [comment]
I tested the snapshot build and I could upload my app bundle without any problems! Thanks for the awesome work!

**Comment by knordbo** [comment]
Change `jsonFile` to `serviceAccountCredentials`

**Comment by hardysim** [comment]
Thx @knordbo - that's helping.

But now I'm running into the next error:

> What went wrong:
A problem was found with the configuration of task ':app:publishReleaseBundle'.
Directory 'app\build\generated\gpp\release\res\release-notes' specified for property 'releaseNotesDir$plugin' does not exist.

Is there a readme / howto on how to migrate to 2.0.0? I've only found the [CHANGELOG](https://github.com/Triple-T/gradle-play-publisher/blob/master/CHANGELOG.md) but there's nothing about the `release-notes`.

**Comment by hardysim** [comment]
Hmm, I cannot find a corresponding issue for the `release-notes` folder (only #361 when the whole `play`-folder is missing).

I found out, that I needed to create the file `src/main/play/release-notes/en-US/default`. With that, the publishing works and an App Bundle is pushed to the store 🎉.

**Comment by knordbo** [comment]
Yup that is the workaround. Issue #361 is indeed the problem. It appears to be marked resolved, but as you point out the issue still remains.

**Comment by hardysim** [comment]
Will there be a new release with this included?
