### ISSUE TITLE
Unexpected Character Exception

### ISSUE THREAD

**Issue by claucookie** [Triple-T/gradle-play-publisher#265]
Hi,

I am unable to publish the APK to google play anymore due to this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':busuuAndroidApp:publishApkRelease'.
> com.fasterxml.jackson.core.JsonParseException: Unexpected character ('s' (code 115)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
   at [Source: java.io.ByteArrayInputStream@1d9c790b; line: 1, column: 2]
```
Could you let me know if you experienced this issue before?

Thanks so much in advance.

Let me attach the full log
```
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('s' (code 115)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.ByteArrayInputStream@49e88fa4; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1378)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:599)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:520)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2275)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:788)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:674)
	at com.google.api.client.json.jackson2.JacksonParser.nextToken(JacksonParser.java:55)
	at com.google.api.client.json.JsonParser.startParsing(JsonParser.java:221)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:380)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:355)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:87)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.fromStream(GoogleCredential.java:250)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential$fromStream.call(Unknown Source)
	at de.triplet.gradle.play.AndroidPublisherHelper.authorizeWithServiceAccount(AndroidPublisherHelper.groovy:66)
	at de.triplet.gradle.play.AndroidPublisherHelper.authorizeWithServiceAccount(AndroidPublisherHelper.groovy:45)
	at de.triplet.gradle.play.AndroidPublisherHelper.init(AndroidPublisherHelper.groovy:86)
	at de.triplet.gradle.play.PlayPublishTask.publish(PlayPublishTask.groovy:28)
	at de.triplet.gradle.play.PlayPublishTask$publish.callCurrent(Unknown Source)
	at de.triplet.gradle.play.PlayPublishApkTask.publishApks(PlayPublishApkTask.groovy:21)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	... 44 more
```

**Comment by claucookie** [comment]
Thanks, we are taking a look at that. At the moment, the file is stored on a jenkins machine which I don't have access I need to wait for my colleague feedback.

**Comment by bhurling** [comment]
From the stacktrace it looks like it's trying to read the jsonFile from something like `yourAccountConfig` as shown below

```
android {
    playAccountConfigs {
        yourAccountConfig {
            jsonFile = file('keys.json')
        }
    }
}
```

**Comment by claucookie** [comment]
@bhurling Thanks so much, it seems like the credentials file was corrupted some how. We successfully published the apk after getting a new credentials file.
