### ISSUE TITLE
HTTP 400: staged rollout with country targeting cannot be updated via API

### ISSUE THREAD

**Issue by michael-mohemian** [Triple-T/gradle-play-publisher#413]
### Describe the bug

Google API reports `Staged rollout with country targeting cannot be updated via API`.

```
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "androidpublisher",
    "message" : "Staged rollout with country targeting cannot be updated via API",
    "reason" : "stagedCountryTargetingNotSupported"
  } ],
  "message" : "Staged rollout with country targeting cannot be updated via API"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$execute.call(Unknown Source)
        at de.triplet.gradle.play.PlayPublishTask.publish(PlayPublishTask.groovy:37)
        at de.triplet.gradle.play.PlayPublishTask$publish.callCurrent(Unknown Source)
        at de.triplet.gradle.play.PlayPublishApkTask.publishApks(PlayPublishApkTask.groovy:21)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        ... 42 more
```

### To Reproduce

The configuration is as following and worked flawlessly the last months. Always reproducable.
```
play {
  jsonFile = file('play.json')
  track = 'internal'
}
```

#### Versions

 - Gradle Play Publisher: 1.2.2
 - Gradle Wrapper (if applicable): 4.5.1
 - Android Gradle Plugin (if applicable): 3.0.1

### Expected behavior

APK being uploaded to Google Play.

**Comment by SUPERCILEX** [comment]
Can you try the 2.0 [snapshot builds](https://github.com/Triple-T/gradle-play-publisher/tree/07c24efd424473bd1f16a709c936c0fe7ee7f3da#snapshot-builds)? See this [migration guide](https://github.com/Triple-T/gradle-play-publisher/blob/master/CHANGELOG.md#breaking-changes).

**Comment by SUPERCILEX** [comment]
Closing for now since we're not going to support 1.x versions. Please let us know if this is still happening on 2.x.

**Comment by michael-mohemian** [comment]
We tried `2.0.0-beta1` and can confirm that the issue has been fixed, thanks a lot 🙌
