### ISSUE TITLE
Issues running tests locally

### ISSUE THREAD

**Issue by NiciDieNase** [Triple-T/gradle-play-publisher#476]
When trying to run the tests on my machine multiple test fail.
CompatibilityTest fails with NoSuchElementException in all three cases.
```
java.util.NoSuchElementException: Array contains no element matching the predicate.
	at com.github.triplet.gradle.play.CompatibilityTest.pluginTest(CompatibilityTest.kt:121)
	at com.github.triplet.gradle.play.CompatibilityTest.pluginIsCompatible(CompatibilityTest.kt:33)
      [...]
java.util.NoSuchElementException: Array contains no element matching the predicate.
	at com.github.triplet.gradle.play.CompatibilityTest.pluginTest(CompatibilityTest.kt:121)
	at com.github.triplet.gradle.play.CompatibilityTest.pluginIsCompatible(CompatibilityTest.kt:33)
      [...]
java.util.NoSuchElementException: Array contains no element matching the predicate.
	at com.github.triplet.gradle.play.CompatibilityTest.pluginTest(CompatibilityTest.kt:121)
	at com.github.triplet.gradle.play.CompatibilityTest.pluginIsCompatible(CompatibilityTest.kt:33)
      [...]
```

I could fix this by manually setting the VERSION_NAME-property, but should this not be done automatically or via some properties-file?

Additionally all tests in GenerateResourcesTest, PlayPublishTaskTest and PlayPublisherPluginTest all fail with an Exception in TestHelper:
```
org.gradle.api.plugins.UnknownPluginException: Plugin with id 'com.github.triplet.play' not found.
	...
	at com.github.triplet.gradle.play.TestHelper.evaluatableProject(TestHelper.groovy:24)
	at com.github.triplet.gradle.play.TestHelper$evaluatableProject.call(Unknown Source)
	[...]
	at com.github.triplet.gradle.play.GenerateResourcesTest.testResourcesAreCopiedIntoOutputFolder(GenerateResourcesTest.groovy:13)
         [...]
```
I didn't find a way to fix that. Am I missing some project-setup?

**Comment by NiciDieNase** [comment]
I see that VERSION_NAME should be set by
````
tasks.withType<Test> {
    // Our integration tests need a fully compiled jar
    dependsOn("assemble")

    // Those tests also need to know which version was built
    systemProperty("VERSION_NAME", version)
}
```
and I was running the tests directly from intellij.
Also my ANDROID_HOME was not set.
