### ISSUE TITLE
Invalid service account credential

### ISSUE THREAD

**Issue by cbouyssi** [Triple-T/gradle-play-publisher#483]
### Describe the bug

Build fails saying the service account credentials are invalid.

### To Reproduce

- I added the dependencies to my project
- created a service account on the google console
- generated a Json key (that I linked to the settingAccountCredentials field of the "Play" section)
- ran "gradlew publishApk" 

#### Versions

 - Gradle Play Publisher: 2.0.0
 - Gradle Wrapper (if applicable):/
 - Android Gradle Plugin (if applicable):/

### Expected behavior

A release of the new APK on google play

### Additional context
I'm not sure if it's the proper place to ask this, so if not let me know where I should rather go.
I probably forgot something during the set up. The generated logs are : 
C:\aes\aes-project>gradlew publish

> Configure project :app 
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Signing not ready. Be sure to specify a signingConfig for Release

> Task :app:processReleaseGoogleServices 
Parsing json file: C:\aes\aes-project\app\google-services.json

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:publishReleaseApk'.
> Invalid service account credentials.

**Comment by SUPERCILEX** [comment]
Can you show your build file?

**Comment by cbouyssi** [comment]
The point of this project was only to introduce CI to an android project so the app is almost empty. I must have forgotten something obvious during the set up. I have tried with both the Json key and the p12 key for the serviceAccountCredentials and have added the dependencies (com.github.triplet.gradle:play-publisher:2.0.0-SNAPSHOT)  & repositories (https://oss.sonatype.org/content/repositories/snapshots)  to my app:module Graddle's file 
Thanks for your fast answer.

Build file : 
----------------------------------------------------------------------------------------------------------

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.github.triplet.play'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.insa.aes_app"
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 5
        versionName "1.5"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
play {
    serviceAccountEmail = "aes-project@api-8203273177806996677-283403.iam.gserviceaccount.com"
    serviceAccountCredentials = file("api-8203273177806996677-283403-3703889c2d0f.p12")
    track = "production"
    releaseStatus = "inProgress"
    resolutionStrategy = "ignore"
}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.google.dagger:dagger:2.13'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.13'
    implementation 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    implementation 'com.google.firebase:firebase-auth:16.1.0'
    implementation 'com.google.firebase:firebase-database:16.0.5'
    implementation 'com.google.firebase:firebase-core:16.0.6'
}

**Comment by 26shruti** [comment]
I am facing the same issue but when I use different serviceAccountCredentials to support app falvors

**Comment by SUPERCILEX** [comment]
Ok, and you're sure the file is in the same folder as your build.gradle?

**Comment by SUPERCILEX** [comment]
@nikedlab what you're doing won't work. Read the [README](https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#using-multiple-service-accounts).

**Comment by cbouyssi** [comment]
Yes, the file is in the same folder. It's been opened but what I'm unsure is if it's the right file.
The JSON key I got from the google console contains the following informations : 

{
  "type": "service_account",
  "project_id": "api-8203273177806996677-283403",
  "private_key_id": "{my key id}",
  "private_key": "-----BEGIN PRIVATE KEY-----\n{my key}\n-----END PRIVATE KEY-----\n",
  "client_email": "aes-project@api-8203273177806996677-283403.iam.gserviceaccount.com",
  "client_id": "115947038187782266878",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/aes-project%40api-8203273177806996677-283403.iam.gserviceaccount.com"
}

To upload my first APK to google play, I used a key that I generated locally : aes-private-key.keystore.

**Comment by SUPERCILEX** [comment]
@cbouyssi that's really weird, can you run the task with `--stacktrace` and share the output here?

**Comment by cbouyssi** [comment]
Sure, here it is : 
C:\aes\aes-project>gradlew publishApk --stacktrace
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :app 
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Signing not ready. Be sure to specify a signingConfig for Release

> Task :app:processReleaseGoogleServices 
Parsing json file: C:\aes\aes-project\app\google-services.json

> Task :app:processReleaseManifest 
C:\aes\aes-project\app\src\main\AndroidManifest.xml:24:9-31:50 Warning:
        activity#com.google.firebase.auth.internal.FederatedSignInActivity@android:launchMode was tagged at AndroidManifest.xml:24 to replace other declarations but no o
ther declaration present

> Task :app:compileReleaseJavaWithJavac 
Note: C:\aes\aes-project\app\src\main\java\com\insa\aes_app\dagger\app\MyApplication.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:publishReleaseApk'.
> Invalid service account credentials.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:publishReleaseApk'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalArgumentException: Invalid service account credentials.
        at com.github.triplet.gradle.play.tasks.internal.PlayPublishTaskBase.read(PlayPublishTaskBase.kt:78)
        at com.github.triplet.gradle.play.tasks.internal.PlayPublishTaskBase.read$default(PlayPublishTaskBase.kt:58)
        at com.github.triplet.gradle.play.tasks.internal.PlayPublishTaskBase.write(PlayPublishTaskBase.kt:87)
        at com.github.triplet.gradle.play.tasks.PublishApk.publishApks(PublishApk.kt:38)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 30 more
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.github.triplet.gradle.play.tasks.internal.PlayPublishTaskBase.read(PlayPublishTaskBase.kt:65)
        ... 44 more

**Comment by SUPERCILEX** [comment]
Oh, wow, we wrote the dumbest error message. Anyway, check that you've added permissions: https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#service-account. If that is the case, I'll fix the error message. 😁

**Comment by cbouyssi** [comment]
Managed to make it work ! It was indeed a problem of permission and a miscommunication with my partner who has the google account.
Thanks for your help !!

**Comment by SUPERCILEX** [comment]
Awesome! I've submitted a PR to fix the confusing error message: #487.
