### ISSUE TITLE
ServiceAccount in JSON file and ServiceAccountEmail in AndroidStudio

### ISSUE THREAD

**Issue by dzinek** [Triple-T/gradle-play-publisher#488]
### Describe the bug
I have configure GPP with ServiceAccount in JSON. It works ok in console with `./gradlew` but when I run AndroidStudio it throws an exception while it tries to refresh Gradle files:

`org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':mobile'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:109)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.onAfterEvaluateFailure(LifecycleProjectEvaluator.java:105)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:87)
	at (...)
Caused by: java.lang.IllegalStateException: PKCS12 credentials must also specify a Service Account email
	at com.github.triplet.gradle.play.PlayPublisherPlugin$applyInternal$1.execute(PlayPublisherPlugin.kt:99)
	at com.github.triplet.gradle.play.PlayPublisherPlugin$applyInternal$1.execute(PlayPublisherPlugin.kt:32)
	at org.gradle.internal.ImmutableActionSet$SingletonSet.execute(ImmutableActionSet.java:155)
	at org.gradle.internal.MutableActionSet.execute(MutableActionSet.java:35)
	at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:228)
	at (...)
`

When I add ServiceAccountEmail, AndroidStudio works ok, but then I get an error in console (as expected):

`* What went wrong:
A problem occurred configuring project ':mobile'.
Json credentials cannot specify a Service Account email`

### To Reproduce

Run refresh Gradle files in AndroidStudio with JSON service account without ServiceAccountEmail.

#### Versions

 - Gradle Play Publisher: 2.0.0
 - Gradle Wrapper (if applicable): 4.8

**Comment by dzinek** [comment]
Ok, I found it.
In com.github.triplet.gradle.play.PlayPublisherPlugin.kt there is a check:
```kotlin
                if (requireCreds().extension.equals("json", true)) {
                    check(serviceAccountEmail == null) {
                        "Json credentials cannot specify a Service Account email"
                    }
                } else {
                    check(serviceAccountEmail != null) {
                        "PKCS12 credentials must also specify a Service Account email"
                    }
                }
```

In my case a JSON file path is set in env variable. And once I run it from the console where this variable is set, the condition recognize that I have a JSON file.
But in AndroidStudio this variable for 99% is not set - so the condition assume that I have a PKCS12 file and it needs an email.

I propose to clearly set if I have a JSON, PKCS12 file or if I have no file set at all. So simply checking if I have JSON, otherwise assuming that I have PKCS12 is not enough.

I am almost sure that when I restart AS with properly env variable set, this bug will no occure. But nevertheless, I think it should be refactor.

**Comment by SUPERCILEX** [comment]
We're fixing this: #461. In the meantime, if the environment variable isn't there, use a default path.
