### ISSUE TITLE
Crash on APK upload

### ISSUE THREAD

**Issue by pavlospt** [Triple-T/gradle-play-publisher#637]
### Describe the bug

I am trying to upload an APK from a specific `buildType` but it fails with a crash. 

#### Versions

- Gradle Play Publisher: 2.3.0
- Gradle Wrapper: 5.5.1
- Android Gradle Plugin: 3.5.0-rc01

#### Tasks executed

```
./gradlew :app:publish[BUILD_TYPE_NAME]Apk -x :app:lintVital[BUILD_TYPE_NAME] --release-name 2.0.1 --track alpha
```

### Expected behavior

Expected that the APK would be uploaded properly or fail with a PlayStore issue!

### Additional context (if a crash, provide stack trace)

```
Caused by: java.lang.NoSuchMethodError: com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder.setBatchPath(Ljava/lang/String;)Lcom/google/api/client/googleapis/services/AbstractGoogleClient$Builder;
        at com.google.api.services.androidpublisher.AndroidPublisher$Builder.setBatchPath(AndroidPublisher.java:8960)
        at com.google.api.services.androidpublisher.AndroidPublisher$Builder.<init>(AndroidPublisher.java:8939)
        at com.github.triplet.gradle.play.tasks.internal.PlayPublishingApiKt.buildPublisher(PlayPublishingApi.kt:88)
        at com.github.triplet.gradle.play.tasks.internal.PlayPublishTaskBase$publisher$2.invoke(PlayPublishTaskBase.kt:22)
        at com.github.triplet.gradle.play.tasks.internal.PlayPublishTaskBase$publisher$2.invoke(PlayPublishTaskBase.kt:12)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.github.triplet.gradle.play.tasks.internal.PlayPublishTaskBase.getPublisher(PlayPublishTaskBase.kt)
        at com.github.triplet.gradle.play.tasks.internal.PlayPublishTaskBase.getOrCreateEditId(PlayPublishTaskBase.kt:26)
        at com.github.triplet.gradle.play.tasks.PublishApk.access$getOrCreateEditId(PublishApk.kt:29)
        at com.github.triplet.gradle.play.tasks.PublishApk$publishApks$1.execute(PublishApk.kt:60)
        at com.github.triplet.gradle.play.tasks.PublishApk$publishApks$1.execute(PublishApk.kt:29)
        at org.gradle.workers.internal.DefaultWorkerExecutor.submit(DefaultWorkerExecutor.java:79)
        at com.github.triplet.gradle.play.tasks.PublishApk.publishApks(PublishApk.kt:151)
```

**Comment by SUPERCILEX** [comment]
Can you try https://github.com/Triple-T/gradle-play-publisher/issues/344#issuecomment-447917493?

**Comment by pavlospt** [comment]
Sure i will give it a try and let you know! Even though we do not have it enabled for that specific buildType!

**Comment by pavlospt** [comment]
@SUPERCILEX It is indeed resolving this issue, the issue that you mentioned! Do you think it might be worth adding it to a section on README since it seems to have caused several issues to be opened :P I failed to find any of them 😞

**Comment by SUPERCILEX** [comment]
I'd rather fix it at the source: I've submitted a CL internally to remove the `firebase-crash` plugin entirely.

**Comment by pavlospt** [comment]
Oh that's great, is there a public link for that CL?

**Comment by SUPERCILEX** [comment]
Lol, no. Though the code is in `third_party` so I don't know why it's not on GitHub.
