### ISSUE TITLE
Promoting artifact issue

### ISSUE THREAD

**Issue by tprochazka** [Triple-T/gradle-play-publisher#685]
I tried to run this command:

`./gradlew promoteArtifact --from-track internal --track alpha  
`

And this is the result:

```
> Task :app:promoteDefaultAReleaseArtifact
Promoting [draft] release (com.a.android.app:[800006230]) from track 'internal' to track 'internal'
Committing changes

> Task :app:promoteDefaultBReleaseArtifact
Promoting [draft] release (com.b.app:[800006230]) from track 'internal' to track 'internal'
Committing changes

> Task :app:promoteDefaultCReleaseArtifact
Promoting [draft] release (com.c.app:[800006230]) from track 'internal' to track 'internal'
Committing changes
```

And it just creates a new draft with the same version as is currently published in an internal release.
So something which doesn't make sense.
Why is there "from track 'internal' to track 'internal'"?

**Comment by SUPERCILEX** [comment]
@tprochazka is this still an issue? If so, can you check your `play` config block to make sure there isn't a hardcoded `promoteTrack`? It could be #739.

**Comment by tprochazka** [comment]
I did not test it since I wrote this report. 
I'm definitely not using "promoteTrack".
I can try it again with next release of my app.

**Comment by SUPERCILEX** [comment]
@tprochazka thanks, please let me know how it goes! And if possible, use the `--info` flag.

**Comment by tprochazka** [comment]
I tested it now. And it for some weird reason it requires to have mapping files. Why?

`* What went wrong:
A problem was found with the configuration of task ':app:promoteSonyReleaseArtifact' (type 'PromoteRelease').
> File 'C:\Development\Projects_com\a\a-cleaner\app\build\outputs\mapping\sonyRelease\mapping.txt' specified for property 'mappingFile$plugin' does not exist.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.internal.execution.WorkValidationException: A problem was found with the configuration of task ':app:promoteSonyReleaseArtifact' (type 'PromoteRelease').
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:71)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:174)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:374)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:361)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:354)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:340)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.InvalidUserDataException: File 'C:\Development\Projects_com\a\a-cleaner\app\build\outputs\mapping\sonyRelease\mapping.txt' specified for property 'mappingFile$plugin' does not exist.
        ... 39 more
`

**Comment by SUPERCILEX** [comment]
@tprochazka Dang, I swear I've fixed that bug like a dozen times. I can repro with a failing test. As a workaround, just run `./gradlew assembleRelease` first so the mapping file is available.

**Comment by SUPERCILEX** [comment]
Alright, that issue has been fixed and shipped in GPP v2.6.1.

**Comment by tprochazka** [comment]
Thanks. Now it works, but it still just create a new draft in the internal stage when I run 
./gradlew promoteArtifact --from-track internal --track alpha

**Comment by tprochazka** [comment]
Here is --info log
https://gist.github.com/tprochazka/147a8bdf57ca1866e59547ad2b91102d

**Comment by SUPERCILEX** [comment]
Not gonna lie, I don't understand how this is possible. You ***100%*** sure you don't have `draft` specified somewhere?

**Comment by tprochazka** [comment]
I publish bundle as draft, then manually publish it to internal track.
Now there is no draft.
And then just run ./gradlew promoteArtifact --from-track internal --track alpha
(from a different machine that did a build and publishes itself)

I have this setup in the build.gradle, so there is only one "draft" which I have there.
```
play {
    serviceAccountCredentials = file('play/avg_play_developer_api.json')
    track = 'internal'
    releaseStatus = 'draft'
    defaultToAppBundles = true
    enabled = false
}
```

But I hope so that releaseStatus  is just for publishing new APK.

**Comment by SUPERCILEX** [comment]
Ohhhhhhh, then the behavior you're seeing is totally normal. There are no smarts when it comes to the release status because that would be too unpredictable. Just run it like this ` ./gradlew promoteArtifact --from-track internal --promote-track alpha --release-status completed`.

**Comment by tprochazka** [comment]
I will try. So then I would expect that
`./gradlew promoteArtifact --from-track internal --promote-track alpha --release-status draft
`
Will end up with draft in alpha track. I mean promoted from internal to alpha like a draft. But it ends up in the internal stack.

**Comment by tprochazka** [comment]
So, sadly still doesn't work
`./gradlew promoteArtifact --from-track internal --promote-track alpha --release-status completed`

Still just create new draft in internal stage rollout also log mentioning this

```
> Task :app:promoteSonyReleaseArtifact
Promoting release from track 'internal'
Updating [draft] release (com.s.cleaner:[800006507]) in track 'internal'

```

First part is correct `Promoting release from track 'internal'`, but the second should mention alpha and not `draft `an `internal`.

**Comment by SUPERCILEX** [comment]
Oh, hold up. Do you have any `playConfigs`? You might be running into #652. Try this:
```sh
./gradlew promoteSonyReleaseArtifact --from-track internal --promote-track alpha --release-status completed
```

**Comment by tprochazka** [comment]
Yes. You have right. If I do it just for one flavor. It works correctly.
So only batch action for all flavors doesn't works.
I just need to add also --release-name because it cannot keep existing one during promoting.
I just was not so brave to test it for moving to production with stage rollout ;-)

**Comment by SUPERCILEX** [comment]
Lol, no worries. I'm planning on fixing that bug after I've finished up adding all the tests.
