### ISSUE TITLE
Publish bundle with AGP 3.6.0-alpha11 fails with java.lang.NoSuchFieldError: BUNDLE

### ISSUE THREAD

**Issue by knordbo** [Triple-T/gradle-play-publisher#695]
### Describe the bug

Publishing has stopped working as this lookup for bundle file fails: https://github.com/Triple-T/gradle-play-publisher/blob/master/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/Agp.kt#L30

### How To Reproduce

Run `publishBundle`

#### Versions

- Gradle Play Publisher: 2.5.0-SNAPSHOT
- Gradle Wrapper: Gradle 5.6.2
- Android Gradle Plugin: 3.6.0-alpha11

#### Tasks executed

`publishBundle`

### Expected behavior

Published bundle

### Additional context (if a crash, provide stack trace)

```
java.lang.NoSuchFieldError: BUNDLE
        at com.github.triplet.gradle.play.tasks.internal.AgpKt.findBundleFile(Agp.kt:30)
        at com.github.triplet.gradle.play.tasks.PublishBundle.getBundle(PublishBundle.kt:35)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1$1.create(AbstractNestedRuntimeBeanNode.java:80)
        at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:467)
```

**Comment by SUPERCILEX** [comment]
Deep, agonized sigh. Will try to fix tonight.
