### ISSUE TITLE
Could not create an instance of type - app:uploadDevReleasePrivateApk

### ISSUE THREAD

**Issue by zkareyes** [Triple-T/gradle-play-publisher#769]
Hi All,

I'm new to this automated publisher.

**Describe the bug:**
`What went wrong: 
Execution failed for task ':app:uploadDevReleasePrivateApk'.
A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishInternalSharingApk$Processor
Could not create an instance of type com.github.triplet.gradle.play.tasks.PublishInternalSharingApk$Processor.`

**Versions:**

- Gradle Play Publisher: 2.6.2
- Gradle Wrapper: 6.1.1

**Task**
 - ./gradlew uploadDevReleasePrivateApk --info --stacktrace

**Additional context**
I'm using AWS codeBuild for this process

**Comment by SUPERCILEX** [comment]
Please share the stack trace.

**Comment by zkareyes** [comment]
Hi @SUPERCILEX! Thanks for the fast response. We tried running **- ./gradlew publishDevReleaseApk --artifact-dir app/build/artifact --stacktrace** task and got this error.

    Execution failed for task ':generateEditForPhDotComDotGlobeDotGlobeathome'.
     A failure occurred while executing com.github.triplet.gradle.play.tasks.GenerateEdit$Generator
     Could not create an instance of type com.github.triplet.gradle.play.tasks.GenerateEdit$Generator.
     com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder.setBatchPath(Ljava/lang/String;)Lcom/google/api/client/googleapis/services/AbstractGoogleClient$Builder;

**Stack trace**

    Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.github.triplet.gradle.play.tasks.GenerateEdit$Generator
    
    Caused by: org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type com.github.triplet.gradle.play.tasks.GenerateEdit$Generator.
   
    Caused by: java.lang.NoSuchMethodError: com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder.setBatchPath(Ljava/lang/String;)Lcom/google/api/client/googleapis/services/AbstractGoogleClient$Builder;
    at com.google.api.services.androidpublisher.AndroidPublisher$Builder.setBatchPath(AndroidPublisher.java:8996)
    at com.google.api.services.androidpublisher.AndroidPublisher$Builder.<init>(AndroidPublisher.java:8975)
    at com.github.triplet.gradle.androidpublisher.internal.AndroidPublisherKt.createPublisher(AndroidPublisher.kt:37)
    at com.github.triplet.gradle.androidpublisher.internal.DefaultPlayPublisher$Factory.create(DefaultPlayPublisher.kt:189)
    at com.github.triplet.gradle.androidpublisher.PlayPublisher$Companion.invoke(PlayPublisher.kt:92)
    at com.github.triplet.gradle.play.tasks.GenerateEdit$Generator.<init>(GenerateEdit.kt:49)
    at com.github.triplet.gradle.play.tasks.GenerateEdit$Generator$Inject.<init>(Unknown Source)

Thanks!

**Comment by SUPERCILEX** [comment]
Ah, see here: https://github.com/Triple-T/gradle-play-publisher/issues/344#issuecomment-452277735
