### ISSUE TITLE
Getting ClassNotFoundException on class "android.view.x" exceptions after move to 3.0.0-SNAPSHOT and Android build tools 4.1 Beta

### ISSUE THREAD

**Issue by peterhav** [Triple-T/gradle-play-publisher#835]
### Describe the bug

By changing my gradle build to Android Studio Build tools and gradle-play-publisher version 3.0.0-SNAPHOST I start getting the following type of exception on 9 out of 13 test devices in my Google Play pre-launch report:

Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.x" on path: DexPathList[[zip file "/data/app/com.xxxx.xxxx-1/base.apk"

I'm not sure if this is due to the android tools or the play publisher.

### How To Reproduce

change: `classpath 'com.android.tools.build:gradle:4.1.0-beta04'` to classpath `'com.android.tools.build:gradle:4.0.0'`

change `classpath("com.github.triplet.gradle:play-publisher:2.8.0")` to `classpath("com.github.triplet.gradle:play-publisher:3.0.0-SNAPSHOT")`

Exceptions seem to occur on ARM64_V8 and ARM_V7 type of devices only (other devices run fine)

#### Versions

- Gradle Play Publisher: 3.0.0-SNAPSHOT
- Gradle Wrapper: 6.5.1
- Android Gradle Plugin:  4.1.0-beta04

#### Tasks executed

gradlew publishRelease

### Expected behavior

No runtime exceptions being introduced when switching to these new tool versions

### Additional context (if a crash, provide stack trace)

The type of exception thrown is:

```
FATAL EXCEPTION: main
Process: com.xxxxxx.xxxx, PID: 15257
android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class x
Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class x
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.x" on path: DexPathList[[zip file "/data/app/com.xxxxxx.xxxx-1/base.apk", zip file "/data/app/com.xxxxxx.xxxx-1/split_config.arm64_v8a.apk", zip file "/data/app/com.xxxxxx.xxxx-1/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.xxxxxx.xxxx-1/lib/arm64, /data/app/com.xxxxxx.xxxx-1/base.apk!/lib/arm64-v8a, /data/app/com.xxxxxx.xxxx-1/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.xxxxxx.xxxx-1/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.view.LayoutInflater.createView(LayoutInflater.java:616)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:711)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:74)
	at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:105)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:728)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:796)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at c.a.a.l.j.n(Unknown Source)
	at com.afollestad.materialdialogs.internal.message.DialogContentLayout.b(DialogContentLayout.kt:21)
	at c.a.a.j.e.a(Unknown Source)
	at c.a.a.j.e.c(Unknown Source)
	at c.b.a.c.b.d$a.a(InstanceChangeDataDialogUtil.kt:14)
	at c.b.a.h.f.a(ToCommonLib.kt:1)
	at androidx.lifecycle.LiveData.c(LiveData.java:6)
	at androidx.lifecycle.LiveData.d(LiveData.java:8)
	at x.r.s.m(MutableLiveData.java:4)
	at c.b.a.a.b.g0.g(InstanceViewModel.kt:4)
	at c.b.a.a.b.i0.a(InstanceViewModel.kt:6)
	at x.r.q$a.a(MediatorLiveData.java:4)
	at androidx.lifecycle.LiveData.c(LiveData.java:6)
	at androidx.lifecycle.LiveData.d(LiveData.java:5)
	at androidx.lifecycle.LiveData$c.b(LiveData.java:9)
	at androidx.lifecycle.LiveData.h(LiveData.java:5)
	at x.r.q.i(MediatorLiveData.java:3)
	at androidx.lifecycle.LiveData$c.b(LiveData.java:5)
	at androidx.lifecycle.LiveData$LifecycleBoundObserver.d(LiveData.java:5)
	at x.r.m$a.a(LifecycleRegistry.java:3)
	at x.r.m.a(LifecycleRegistry.java:12)
	at androidx.lifecycle.LiveData.g(LiveData.java:9)
	at c.i.a.g.o(Unknown Source)
	at c.b.a.c.b.d.a(InstanceChangeDataDialogUtil.kt:8)
	at com.xxxxxx.xxxx.features.instances.RegisterAttendanceFragment$a.onClick(java-style lambda group:14)
	at android.view.View.performClick(View.java:5646)
	at android.view.View$PerformClick.run(View.java:22458)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.xxxxxx.xxxx-1/split_config.arm64_v8a.apk
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:373)
		at dalvik.system.DexFile.<init>(DexFile.java:113)
		at dalvik.system.DexFile.<init>(DexFile.java:78)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:359)
		at dalvik.system.DexPathList.makeElements(DexPathList.java:323)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:263)
		at dalvik.system.DexPathList.<init>(DexPathList.java:126)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
		at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:540)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:573)
		at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1990)
		at android.app.LoadedApk.getResources(LoadedApk.java:799)
		at android.app.ContextImpl.<init>(ContextImpl.java:2217)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:2162)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5547)
		at android.app.ActivityThread.-wrap2(ActivityThread.java)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
		at android.os.Handler.dispatchMessage(Handler.java:105)
		... 5 more
	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.xxxxxx.xxxx-1/split_config.xxhdpi.apk
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:373)
		at dalvik.system.DexFile.<init>(DexFile.java:113)
		at dalvik.system.DexFile.<init>(DexFile.java:78)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:359)
		at dalvik.system.DexPathList.makeElements(DexPathList.java:323)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:263)
		at dalvik.system.DexPathList.<init>(DexPathList.java:126)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
		at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:540)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:573)
		at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1990)
		at android.app.LoadedApk.getResources(LoadedApk.java:799)
		at android.app.ContextImpl.<init>(ContextImpl.java:2217)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:2162)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5547)
		at android.app.ActivityThread.-wrap2(ActivityThread.java)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
		at android.os.Handler.dispatchMessage(Handler.java:105)
		... 5 more
```
Note that I made the switch to 3.0.0-SNAPSHOT due to no longer being able to use 2.8.0:

```
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:publishReleaseBundle'.
> com.android.build.gradle.internal.scope.InternalArtifactType$BUNDLE cannot be cast to com.android.build.api.artifact.ArtifactType
```

**Comment by SUPERCILEX** [comment]
That's not related to this plugin. Why did you downgrade AGP?

**Comment by peterhav** [comment]
> That's not related to this plugin. Why did you downgrade AGP?

Ok thanks. I will further investigate, might be something in the 4.1.0 build tools or Google Play then. Note that I did not downgrade, but upgraded the build tools from 4.0.0 to 4.1.0  (mistake in the issue description)

**Comment by andzejsw** [comment]
> > That's not related to this plugin. Why did you downgrade AGP?
> 
> Ok thanks. I will further investigate, might be something in the 4.1.0 build tools or Google Play then. Note that I did not downgrade, but upgraded the build tools from 4.0.0 to 4.1.0 (mistake in the issue description)

Did you find what was the issue?
