### ISSUE TITLE
Configuration exception with Android Gradle Plugin 4.1: Cannot query the value of this property because it has no value available

### ISSUE THREAD

**Issue by gildor** [Triple-T/gradle-play-publisher#849]
### Describe the bug

Plugin doesn't work with Android Gradle Plugin 4.1.0-rc01, Gradle configuration is failing

### How To Reproduce

- Create a project with AGP 4.1.0-rc01
- Configure gradle-play-publiusher
- ./gradlew :app:publishReleaseBundle
- Gradle build fails during project configuration

#### Versions
- Gradle Play Publisher: 2.8.0
- Gradle Wrapper: 6.6.1
- Android Gradle Plugin: 4.1.0-rc01

#### Tasks executed

./gradlew :app:publishReleaseBundle

### Expected behavior

Publishing works with AGP 4.1

### Additional context

```
Caused by: org.gradle.api.internal.provider.MissingValueException: Cannot query the value of this property because it has no value available.
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:86)
        at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:56)
distributionBase=GRADLE_USER_HOME
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.visitContents(DefaultConfigurableFileCollection.java:300)
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.visitContents(DefaultConfigurableFileCollection.java:224)
        at org.gradle.api.internal.file.CompositeFileCollection.getSourceCollections(CompositeFileCollection.java:145)
        at org.gradle.api.internal.file.CompositeFileCollection.iterator(CompositeFileCollection.java:61)
        at kotlin.collections.CollectionsKt___CollectionsKt.singleOrNull(_Collections.kt:579)
        at com.github.triplet.gradle.play.tasks.internal.UploadArtifactTaskBase.getMappingFile$plugin(UploadArtifactTaskBase.kt:25)
```

**Comment by SUPERCILEX** [comment]
I'm going to release v3 soon which supports this (in the meantime, you can use the snapshots). GPP 2.x won't be supported as AGP 4.1 broke other stuff too.
