### ISSUE TITLE
com.fasterxml.jackson.core.JsonParseException: Unexpected character

### ISSUE THREAD

**Issue by kuFEAR** [Triple-T/gradle-play-publisher#871]
### Describe the bug

After updating plugin to 3.0.0 version, it's become crashing on publishReleaseBundle task with trace

### How To Reproduce

publishReleaseBundle

and task which tried executed generated as generateEditForComDotCompanyDotProject and failed

#### Versions

- Gradle Play Publisher:  3.0.0
- Gradle Wrapper:  6.7
- Android Gradle Plugin: 4.1.0

#### Tasks executed

publishReleaseBundle

### Additional context (if a crash, provide stack trace)

`Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ((CTRL-CHAR, code 130)): Expected space separating root-level values
 at [Source: (FileInputStream); line: 1, column: 3]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:707)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:632)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportMissingRootWS(ParserMinimalBase.java:679)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._verifyRootSpace(UTF8StreamJsonParser.java:1688)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parsePosNumber(UTF8StreamJsonParser.java:1428)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:863)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:757)
        at com.google.api.client.json.jackson2.JacksonParser.nextToken(JacksonParser.java:52)
        at com.google.api.client.json.JsonParser.startParsing(JsonParser.java:213)
        at com.google.api.client.json.JsonParser.parse(JsonParser.java:358)
        at com.google.api.client.json.JsonParser.parse(JsonParser.java:335)
        at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:79)
        at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:73)
        at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:156)
        at com.github.triplet.gradle.androidpublisher.internal.AndroidPublisherKt.createPublisher(AndroidPublisher.kt:25)
        at com.github.triplet.gradle.androidpublisher.internal.DefaultPlayPublisher$Factory.create(DefaultPlayPublisher.kt:226)
        at com.github.triplet.gradle.androidpublisher.PlayPublisher$Companion.invoke(PlayPublisher.kt:101)
        at com.github.triplet.gradle.play.tasks.GenerateEdit$Generator.<init>(GenerateEdit.kt:50)
        at com.github.triplet.gradle.play.tasks.GenerateEdit$Generator$Inject.<init>(Unknown Source)`

**Comment by kuFEAR** [comment]
https://github.com/Triple-T/gradle-play-publisher/commit/12571e46237d5d4a2c092fe3b96923fd2c25d2f4#diff-bf825eb1d57e034da225b73cd9792f90474a5e04317d03ab7f0e4b3be81a180b it’s may be cause

**Comment by kuFEAR** [comment]
oh I see in 3.0.0 we can't use p12 anymore
